### ISSUE TITLE
Create Initial Project Structure

### ISSUE THREAD

**Issue by GOkwori** [GOkwori/AccountSphere#2]
Task: Set up the initial folder and file structure for the project.
Details: Create a structured directory within repository to organize the project into clear sections, such as:
/frontend for all front-end related files (HTML, CSS, JavaScript).
/backend for back-end code (Python+Flask files).
/database for database scripts and schemas.
/docs for project documentation.
Also, add a .gitignore file to exclude files/folders from being tracked by Git, like environment variables or IDE settings.

**Comment by GOkwori** [comment]
Bug: ImportError: cannot import name '_app_ctx_stack' from 'flask'

(venv) Georges-MacBook-Pro:AccountSphere georgeokwori$ python3 run.py
Traceback (most recent call last):
  File "/Users/georgeokwori/Documents/GitHub/AccountSphere/run.py", line 2, in <module>
    from accountsphere import app
  File "/Users/georgeokwori/Documents/GitHub/AccountSphere/accountsphere/__init__.py", line 3, in <module>
    from flask_sqlalchemy import SQLAlchemy
  File "/Users/georgeokwori/Documents/GitHub/AccountSphere/venv/lib/python3.12/site-packages/flask_sqlalchemy/__init__.py", line 14, in <module>
    from flask import _app_ctx_stack, abort, current_app, request
ImportError: cannot import name '_app_ctx_stack' from 'flask' (/Users/georgeokwori/Documents/GitHub/AccountSphere/venv/lib/python3.12/site-packages/flask/__init__.py)

**Comment by GOkwori** [comment]
> Bug: (venv) Georges-MacBook-Pro:AccountSphere georgeokwori$ python3 run.py Traceback (most recent call last): File "/Users/georgeokwori/Documents/GitHub/AccountSphere/run.py", line 2, in from accountsphere import app File "/Users/georgeokwori/Documents/GitHub/AccountSphere/accountsphere/**init**.py", line 3, in from flask_sqlalchemy import SQLAlchemy File "/Users/georgeokwori/Documents/GitHub/AccountSphere/venv/lib/python3.12/site-packages/flask_sqlalchemy/**init**.py", line 14, in from flask import _app_ctx_stack, abort, current_app, request ImportError: cannot import name '_app_ctx_stack' from 'flask' (/Users/georgeokwori/Documents/GitHub/AccountSphere/venv/lib/python3.12/site-packages/flask/**init**.py)

Bug resolved: [notice] To update, run: pip install --upgrade pip
(venv) Georges-MacBook-Pro:AccountSphere georgeokwori$ 
(venv) Georges-MacBook-Pro:AccountSphere georgeokwori$ pip install --upgrade pip
Requirement already satisfied: pip in ./venv/lib/python3.12/site-packages (23.2.1)
Collecting pip
  Obtaining dependency information for pip from https://files.pythonhosted.org/packages/8a/6a/19e9fe04fca059ccf770861c7d5721ab4c2aebc539889e97c7977528a53b/pip-24.0-py3-none-any.whl.metadata
  Using cached pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.2.1
    Uninstalling pip-23.2.1:
      Successfully uninstalled pip-23.2.1
Successfully installed pip-24.0
(venv) Georges-MacBook-Pro:AccountSphere georgeokwori$ python3 run.py
 * Serving Flask app 'accountsphere'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.20.10.2:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 827-364-422

**Comment by GOkwori** [comment]
Bug: Encountering 404 errors when trying to access the root URL (/). 

* Restarting with stat
 * Debugger is active!
 * Debugger PIN: 827-364-422
127.0.0.1 - - [08/Apr/2024 05:57:04] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2024 05:57:10] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2024 05:57:13] "GET / HTTP/1.1" 404 -
172.20.10.2 - - [08/Apr/2024 05:57:32] "GET / HTTP/1.1" 404 -
172.20.10.2 - - [08/Apr/2024 05:57:33] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [08/Apr/2024 05:57:54] "GET / HTTP/1.1" 404 -

**Comment by GOkwori** [comment]
> Bug: Encountering 404 errors when trying to access the root URL (/).
> 
> * Restarting with stat
> * Debugger is active!
> * Debugger PIN: 827-364-422
>   127.0.0.1 - - [08/Apr/2024 05:57:04] "GET / HTTP/1.1" 404 -
>   127.0.0.1 - - [08/Apr/2024 05:57:10] "GET / HTTP/1.1" 404 -
>   127.0.0.1 - - [08/Apr/2024 05:57:13] "GET / HTTP/1.1" 404 -
>   172.20.10.2 - - [08/Apr/2024 05:57:32] "GET / HTTP/1.1" 404 -
>   172.20.10.2 - - [08/Apr/2024 05:57:33] "GET /favicon.ico HTTP/1.1" 404 -
>   127.0.0.1 - - [08/Apr/2024 05:57:54] "GET / HTTP/1.1" 404 -

Bug fixed.
